application: fotoques
version: 1
runtime: python
api_version: 1

handlers:

- url: /test-useraccount
  script: tests/UserAccountTest.py

- url: /images
  static_dir: images
  
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /admin.*
  script: admin.py

- url: /.*
  script: home.py
  
builtins:
- datastore_admin: on