application: fotoques
version: 1
runtime: python
api_version: 1

handlers:
- url: /images
  static_dir: images
  
- url: /css
  static_dir: css

- url: /js
  static_dir: js
  
- url: /test
  script: test.py
  
- url: /appengine_admin_media
  static_dir: appengine_admin/media
  secure: never 
 
- url: /admin.*
  script: admin.py

- url: /.*
  script: home.py